services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.5-management

    ports:
      - '15672:15672'  # Porta para o console de gerenciamento do RabbitMQ
      - '5672:5672'    # Porta para AMQP
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados
      - rabbitmq_logs:/var/log/rabbitmq  # Logs do RabbitMQ
    networks:
      - mynetwork


  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'  # Porta para SMTP
      - '8025:8025'  # Porta para o console de gerenciamento do MailHog (interface web)

networks:
  mynetwork:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local